### ISSUE TITLE
NoSuchMethodError exception when invoked from Java (Jetty)

### ISSUE THREAD

**Issue by berezovskyi** [labra/shaclex#16]
Hello Jose,

We are trying to call shaclex from a java webapp project running inside jetty, but getting the following exception:

```
java.lang.NoSuchMethodError: es.weso.typing.Typing.getMap()Lscala/collection/immutable/Map;
	at es.weso.schema.ShaclexSchema.cnvShapeTyping(ShaclexSchema.scala:33)
	at es.weso.schema.ShaclexSchema$$anonfun$cnvResult$1.apply(ShaclexSchema.scala:28)
	at es.weso.schema.ShaclexSchema$$anonfun$cnvResult$1.apply(ShaclexSchema.scala:28)
	at scala.collection.immutable.List.map(List.scala:273)
	at es.weso.schema.ShaclexSchema.cnvResult(ShaclexSchema.scala:28)
	at es.weso.schema.ShaclexSchema.validateTargetDecls(ShaclexSchema.scala:21)
	at es.weso.schema.Schema.validateWithTrigger(Schema.scala:22)
	at es.weso.schema.Schema.validate(Schema.scala:39)
	at your.basepackage.name.SampleAdaptorManager.getServiceProviderInfos(SampleAdaptorManager.java:108)
```

POM file: [pom.xml.zip](https://github.com/labra/shaclex/files/674269/pom.xml.zip)

shaclex jars were installed locally this way: https://gitlab.com/assume/shaclex/tree/fixmvn#local-m2-installation (which was probably far from optimal)

cc @jadelkhoury

**Comment by berezovskyi** [comment]
These are the jars that are packaged in the WAR file:

```
ᐅ l WEB-INF/lib | grep scala
json4s-scalap_2.11-3.3.0.jar
org.scala-lang-scala-library-2.11.8.jar
org.typelevel-scala-library-2.11.8.jar
scala-compiler-2.11.8.jar
scala-java8-compat_2.11-0.5.0.jar
scala-logging_2.11-3.5.0.jar
scala-parser-combinators_2.11-1.0.4.jar
scala-reflect-2.11.8.jar
scala-xml_2.11-1.0.4.jar
scalacheck_2.11-1.13.4.jar
scalactic_2.11-3.0.0.jar
scalaz-concurrent_2.11-7.2.5.jar
scalaz-core_2.11-7.2.6.jar
scalaz-effect_2.11-7.2.5.jar
scalaz-stream_2.11-0.8.4a.jar
```

**Comment by labra** [comment]
It looks as a problem with the packaged Jars. I will see if I can reproduce it. 

You may try to generate a fat jar from `sbt` using. 

```
sbt assembly
```

Anyway, I will try to create a simpler interface to enable better interoperability from Java applications. See  issue #17

**Comment by berezovskyi** [comment]
Thank you! I was thinking that I did something wrong with the SBT config.

This is the minimal webapp project that uses shaclex: https://gitlab.com/assume/adaptor-shacl

I will try `sbt assembly` to compare the contents of the fat jar from sbt and our war. I think publishing to bintray might solve these errors (#18).

**Comment by berezovskyi** [comment]
The bug in my code seems to be hitting this: https://github.com/labra/shaclex/commit/afc1e5549b2dbaa2c9d85117d2cb29a1e83342cc

I built my local jars from master and I must have built not all the projects and the missing ones (from the commit above it seems to be shex) must have been loaded from bintray. Could you please tag the revision, which corresponds to 0.0.55 on bintray, please?

But I tried using 0.0.54 from bintray and got the following:

```
Caused by: java.lang.NoSuchMethodError: es.weso.typing.Typing$.empty(Lcats/Show;Lcats/Show;Lcats/Show;Lcats/Show;)Les/weso/typing/Typing;
	at es.weso.shacl.Validator.runCheck(ValidatorCats.scala:69)
	at es.weso.shacl.Validator.validateAll(ValidatorCats.scala:608)
	at es.weso.schema.ShaclexSchema.validate(ShaclexSchema.scala:20)
	at your.basepackage.name.SampleAdaptorManager.getServiceProviderInfos(SampleAdaptorManager.java:133)
	at your.basepackage.name.servlet.ServiceProviderCatalogSingleton.initServiceProviders(ServiceProviderCatalogSingleton.java:276)
	at your.basepackage.name.servlet.ServiceProviderCatalogSingleton.getServiceProviderCatalog(ServiceProviderCatalogSingleton.java:104)
	at your.basepackage.name.services.ServiceProviderCatalogService.getHtmlServiceProvider(ServiceProviderCatalogService.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

I also copied your code from apiShaclex almost verbatim, so I start to suspect Jetty/Scala problems or I might have messed up with the exclusions.

apiShaclex is a very good starting point for using shaclex library in general (thank you!). I think both links to it and to https://bintray.com/labra/maven/shaclex# should be in the readme.

**Comment by labra** [comment]
I have just published version [0.0.56](https://bintray.com/labra/maven/shaclex/0.0.56) with the latest code in the repository. Could you try it?

My concern is that the jar published only contains the files of that module and omits the rest of the modules in the library which are published in different places, for example, shex code is published [here](https://bintray.com/labra/maven/shex/0.0.56) and so on...in principle, Maven should take care of the dependencies, but I am not sure if there could be some hidden problem related with the use of the Typelevel compiler. 

You may have seem that I created a new issue to update the code to use the latest Scala 2.12 compiler. I am planning to do that in the next days once I check that all the libraries have been published for 2.12 also.

**Comment by berezovskyi** [comment]
Thank you for such a quick reply!

I tried it and it doesn't help. To move our debugging effort forward, here is a clean repo without jax-rs with just 3 unit tests and a reproducible build: https://gitlab.com/assume/shacl-try-standalone.

I looked at https://dl.bintray.com/labra/maven/es/weso/ (I added the `https://dl.bintray.com/labra/maven/` repo to my pom file) and all the libraries seem to be there.

Can't really comment on Typelevel compiler and/or on its version as I have no idea what impact do they have.

cc @jadelkhoury

**Comment by labra** [comment]
Thanks! Iwill try to see if I can spot the problem...although I suspect there may be some internal problem in the compiler and it may be better to just update the compiler to Scala 2.12...this action will take me some time but the effort may be worthwhile in the long term.

**Comment by labra** [comment]
I have just updated to Scala 2.12 compiler and published a new version 0.0.57. Could you try it with the new version?

**Comment by berezovskyi** [comment]
Thank you for the update! There seem to be 3 problems:

- maven tries to resolve `com.typesafe.play:twirl-api_2.12:jar:1.2.0` (which should be 1.3.0 - https://www.mvnrepository.com/artifact/com.typesafe.play/twirl-api_2.12/1.3.0).
- maven tries to include some 2.10.x and 2.11.x dependencies still.
- maven doesn't fail the build due to the first problem on my machine, so I might have some .m2 cleaning to do.

Full build log is available at https://gitlab.com/assume/shacl-try-standalone/builds/8340198

**Comment by labra** [comment]
I have just published version 0.0.58 which fixes the problem with the twirl-api jar and now uses 1.30 (thanks for reporting it).

Anyway, the bad news is that the original problem remains. 

I have updated this old project called [shexjava](https://github.com/labra/shexjava) where I just call the library from a simple command line java program and it also raises the exception:

```
Exception in thread "main" java.lang.NoSuchMethodError: es.weso.typing.Typing.getMap()Lscala/collection/immutable/Map;
        at es.weso.schema.ShExSchema.cnvShapeTyping(ShExSchema.scala:41)
        at es.weso.schema.ShExSchema.$anonfun$cnvResult$1(ShExSchema.scala:36)
        at scala.collection.immutable.List.map(List.scala:272)
        at es.weso.schema.ShExSchema.cnvResult(ShExSchema.scala:36)
        at es.weso.schema.ShExSchema.validateTargetDecls(ShExSchema.scala:27)
        at es.weso.schema.Schema.validateWithTrigger(Schema.scala:22)
        at es.weso.schema.Schema.validate(Schema.scala:39)
        at es.weso.shexjava.ShExValidator.validate(ShExValidator.java:27)
        at es.weso.shexjava.ShExValidator.validate(ShExValidator.java:48)
        at es.weso.shexjava.Main.main(Main.java:34)
```

So now, it is working with the Scala 2.12 compiler and we can discard a problem with a compiler plugin that I was suspecting. 

At this moment I have no clue why it doesn't find that method 😕

**Comment by berezovskyi** [comment]
I looked a lot through similar questions on SO and in most cases the solution was to change some library version. If you search for "2.10" or "2.11", you'll find a lot of results in your build log: https://travis-ci.org/labra/shaclex

I discovered https://github.com/jrudolph/sbt-dependency-graph and will try checking the dependencies thoroughly.

**Comment by labra** [comment]
I think I have found (and solved) the problem. It was a duplicated set of files which where both in the `rbe...` and `typing...` jars and made their corresponding classes to overlap.

I have published version 0.0.60 which I think works. 

Could you try it?

**Comment by berezovskyi** [comment]
Great! 0.0.60 works like a charm! https://gitlab.com/assume/shacl-try-standalone build passes now. Not sure if it could become a good sample Java app for the library in the future, we plan to do some simple tests with Jena model. 

CC @jadelkhoury
